### PR TITLE
Add project logo

### LINKED ISSUE #357: Get a project logo
To make it official ;)

### PR DESCRIPTION
**Pull request by qualidafial**
Fixes #357 

@stevenschlansker or @arteam: please review

### CODE REVIEW

**Comment by qualidafial** [comment]
@stevenschlansker Do you want to set this logo on the Github org?

**Comment by stevenschlansker** [comment]
@qualidafial GitHub forces it to be a square... no matter what size you render it in it makes you crop it :cry:

**Comment by qualidafial** [comment]
I can pad the graphic. Stand by..

**Comment by qualidafial** [comment]
@stevenschlansker Try this svg:

```svg
<svg xmlns="http://www.w3.org/2000/svg"
     id="svg"
     version="1.1"
     width="140"
     height="140"
     style="display: block;">
    <g id="svgg">
        <!-- dots -->
        <path id="path0"
              d="M  10 25
                 L  10 35
                 L  20 35
                 L  20 25
                 L  10 25

                 M 130 25
                 L 130 35
                 L 140 35
                 L 140 25
                 L 130 25"
              stroke="none"
              fill="#c00"
              fill-rule="evenodd">
        </path>

        <!-- letters -->
        <path id="path1"
              d="M   0 105
                 L   0 115
                 L  20 115
                 L  20  55
                 L  10  55
                 L  10 105
                 L   0 105

                 M  60  25
                 L  60  55
                 L  30  55
                 L  30  95
                 L  70  95
                 L  70  73.571
                 L  60  70.714
                 L  60  85
                 L  40  85
                 L  40  65
                 L  70  65
                 L  70  25
                 L  60  25

                 M  80  25
                 L  80  76.428
                 L  90  79.285
                 L  90  65
                 L 110  65
                 L 110  85
                 L  80  85
                 L  80  95
                 L 120  95
                 L 120  55
                 L  90  55
                 L  90  25
                 L  80  25

                 M 130  75
                 L 130  95
                 L 140  95
                 L 140  55
                 L 130  55
                 L 130  75"
              stroke="none"
              fill="#005"
              fill-rule="evenodd">
        </path>
    </g>
</svg>
```

**Comment by qualidafial** [comment]
@stevenschlansker ping

**Comment by stevenschlansker** [comment]
Fixed

**Pull request merged**
