### PR TITLE
DefineNamedBindings: check getConnction works (e.g. sql array uses it)

### PR DESCRIPTION
**Pull request by stevenschlansker**

### CODE REVIEW

**Comment by TheRealMarnes** [comment]
Is it worth it to add a test that actually performs the usecase that made you do this, instead of only a standalone assertion?

**Comment by stevenschlansker** [comment]
It's a pain because it actually works just fine in `h2` since it binds it as `Object[]`.  I could spin up a Postgres test, but it'd end up spinning up a database just to ensure a `SqlArray` gets called... this test seemed like a minimal compromise.

**Comment by TheRealMarnes** [comment]
Well we have other databases than heavy postgres too. Sqlite for one, or we could merge my hsqldb integration soon.

**Comment by stevenschlansker** [comment]
Sqlite doesn't even have types... does it have any array support at all?
Postgres is the only database I have experience using arrays with.

**Comment by stevenschlansker** [comment]
sure, we can definitely improve it later, if hsqldb makes it easy to write a better test.

**Pull request merged**
