### PR TITLE
Add 5-minute tour doc

### PR DESCRIPTION
**Pull request by qualidafial**

### CODE REVIEW

**Comment by qualidafial** [comment]
I pushed the doc changes to `jdbi.github.io`. Have a look when you get a moment.

**Comment by stevenschlansker** [comment]
Nice!

**Comment by qualidafial** [comment]
Let me know if you find a way to suppress leading indentation on an include, or on the code renderer, so I can format the .java files properly.

**Comment by stevenschlansker** [comment]
@qualidafial you can do it with `[source,java,indent=0]`

**Comment by qualidafial** [comment]
Nice! And I see you've gone through and cleaned up the existing ones.

**Pull request merged**
