### PR TITLE
first pass at jdbi3-asciidoc

### LINKED ISSUE #310: Migrate jdbi-docs to Github Pages
As discussed in another issue, our documentation is rather out of date, and in a format that requires manual work to deploy.

I propose migrating our documentation to Github Pages, using AsciiDoc format.
- [x] Set up docs artifact with scripts to build and publish documentation to Github Pages.
- [x] Introduction
- [x] 5-minute tour
- ~v2 to v3 migration guide~ #715 
- ~Developer Guide~ #716
- [x] Reference
  - [x] Core (Fluent) API
    - [x] DBI
    - [x] Handle
    - ~Query~ #717
    - ~Update~ #718
    - ~Call~ #720
    - ~Script~ #721
    - ~Batch~ #722
    - [x] Adding support for custom types
      - [x] Arguments
      - [x] Mappers
      - ~Collectors~ #726
    - ~Extensions~ #724
      - ~Attach vs on-demand~
    - ~Plugins~ #725
      - ~`DBI.addPlugin(JdbiPlugin)` vs `DBI.addPlugins()` magic~
  - ~Extensions~
    - ~SQL Object~ #727
      - ~All the annotations~
      - ~Mixins: `GetHandle` and `Transactional`~
      - ~SqlObject interface~
    - ~Writing an extension?~ #728
  - ~Errata~
    - ~Statement locators~ #729
    - ~Statement rewriters~ #730
    - ~Statement context~ #731

### PR DESCRIPTION
**Pull request by stevenschlansker**
Purports to fix #310.  Someday.  Maybe.

Quick test:
`jdbi3/docs$   mvn deploy -Dmaven.deploy.skip=true -Ppublish-docs`

### CODE REVIEW

**Comment by qualidafial** [comment]
When this is ready, we should put docs in their own repository called `jdbi.github.io`. This will cause the domain `https://jdbi.github.io` to render the documentation as a full web site.

Also, The official AsciiDoc file extension is `.adoc`.

**Comment by stevenschlansker** [comment]
@qualidafial this is obviously not done by any means, but it works, and maybe you should test to see if you can publish docs easily?   Then consider merging so we can keep PRs small.

**Comment by qualidafial** [comment]
@stevenschlansker I tried running the publish-docs.sh script, but was denied access to the repository.

**Comment by stevenschlansker** [comment]
try again? should be fixed

**Comment by qualidafial** [comment]
Yep, it's working now.

**Pull request merged**
