### PR TITLE
[wip] PMD #1

### PR DESCRIPTION
**Pull request by TheRealMarnes**

### CODE REVIEW

**Comment by TheRealMarnes** [comment]
Double-checked all changes this time

**Comment by TheRealMarnes** [comment]
Interesting... I need to exclude the generated lexer classes

**Comment by TheRealMarnes** [comment]
Come to think of it, member order is a checkstyle concern, not pmd... Removing that change

**Comment by qualidafial** [comment]
Thanks!

**Comment by TheRealMarnes** [comment]
Lol, I was still working on this after removing the checkstyle commit freed up a lot of the 300 lines quota. Hence the wip tag :p Ah well, onto the next PR. Gotta live dem nice git mechanics

**Pull request merged**
