### PR TITLE
Add usage documentation for @BindList

### PR DESCRIPTION
**Pull request by pikzen**
Explain how @BindList is used, as the need to use `<binding>` might be slightly confusing at first.

Edit: Related to https://github.com/jdbi/jdbi/issues/1010

### CODE REVIEW

**Comment by alwins0n** [comment]
I think the documentation is missing for the fluent API as well, iirc.

**Comment by pikzen** [comment]
I have never had to use BindList with the fluent API :D. I'll be testing things out later in the day and completing the docs to make sure I'm not making any errors in the docs, although I would assume the usage is the same.

**Comment by alwins0n** [comment]
okay, i was just pointing out that it should be mentioned in the "Core API" section (3.), since SQLObject is just an extension of that. (but could be mentioned there as well, like you did)

**Comment by pikzen** [comment]
Alright, included it into the Core API section, and rebased it onto a single commit.

**Comment by alwins0n** [comment]
you should check the file again. seems like you have some git change artifacts in there

**Comment by pikzen** [comment]
Indeed, I seem to have failed at git for a second here :D

All fixed, thanks for the warning.

**Comment by pikzen** [comment]
Done!

**Comment by qualidafial** [comment]
Thanks for the PR!

**Pull request merged**
