### PR TITLE
Add stream wrappers which close streams automatically after terminal operations

### PR DESCRIPTION
**Pull request by qualidafial**
Adds a wrapper around streams returned from ResultBearing.stream() which automatically closes a stream before returning from any call a terminal operation.

Also documents requirement to explicitly close query streams.

### CODE REVIEW

**Comment by qualidafial** [comment]
The intention here is not to absolve users of the requirement to close their streams, but to help them out when they forget.

There are still a few ways that query streams can be used that will not auto-close:
* If an exception is thrown prior to the terminal operation method call
* If users call the `iterator()` or `spliterator()` methods on the stream.

And possibly some other cases I haven't contemplated.

**Comment by qualidafial** [comment]
@stevenschlansker Any concerns before I merge this?

**Comment by stevenschlansker** [comment]
Hm.  I'm a little worried.

This introduces significant complexity, and doesn't absolve the user of the need to close streams.
For example,
```
Stream s = dao.stream(); // returns self-closing stream
s = s.limit(computeSomeLimit()); // computeSomeLimit() throws!
s.collect(...); // Would clean up here, but we bombed!
```

I worry that any place this code is actually used, we have the potential to leak resources when things go wrong.
I know it's nice to be helpful and close streams in the good case, but I worry that it only helps out people that have fundamentally broken code :/

**Comment by stevenschlansker** [comment]
I'm tempted to just say "Stream objects hold heavyweight database resources, and must be used in a `try-with-finally` or otherwise disposed of correctly".  But I'm also a fan of usable software, and I'm waffling...

**Comment by qualidafial** [comment]
We don't have to force through the self-closing streams if you're uneasy about it, although there are other changes I do think are critical:

* Adding `Stream.onClose` handler that closes the ResultIterator
* Modifying the unit tests that call `Query.stream()` to use try-with-resources blocks.

**Comment by qualidafial** [comment]
Opened PR #274

**Comment by qualidafial** [comment]
This PR now only adds self-closing streams on terminal operations.

It's only a hunch, but I seem to be getting more reliable builds (i.e. no timeouts) with this change, FWIW.

**Comment by qualidafial** [comment]
I wonder whether the statement will get cleaned up on exit from a handle or SQL object try-with-resources:

    try (Handle handle = dbi.open()) {
      return handle.createQuery(sql)
        .bind("name", arg)
        .stream()
        .limit(computeLimit()) // throws exception
        .collect(toList());
    }

    try (MyDao dao = dbi.open(MyDao.class)) {
      return dao.stream(arg)
        .limit(computeLimit()) // throws exception
        .collect(toList());
    }

If so, this might provide a palatable alternative to putting all query streams into try-with-resource blocks.

**Comment by stevenschlansker** [comment]
I think by the spec if you close the `Connection` you don't have to close any e.g. `Statement` or `ResultSet` resources, they will be freed -- but I know of at least one connection pool that violates that because "it's too slow"

**Comment by stevenschlansker** [comment]
tag @arteam @brianm @hgschmie anyone got any opinions here?

**Comment by qualidafial** [comment]
What if we introduced a callback method similar to the `withHandle`?

    interface StreamCallback<T, R> {
      R withStream(Stream<T> stream) throws Exception;
    }
    class ResultBearing {
      <T, R> R withStream(StreamCallback<T, R> callback) {
        try (Stream<T> stream = stream()) {
          return callback.withStream(stream);
        }
      }
    }

**Comment by stevenschlansker** [comment]
I like that.  We'd probably still want to have a way to just return the `Stream` though?  For more advanced users who want to control the lifecycle themselves.

Then people can opt-in to the resource management, we don't have wrapper classes, but we have a nicer way to write things safely.

**Comment by qualidafial** [comment]
Already working on it. I'm adding both `withStream` and `useStream` variants just like with handles and transactions.

**Comment by qualidafial** [comment]
Do we want to do anything with SQL objects returning string?

**Comment by stevenschlansker** [comment]
We could allow them to take a `StreamConsumer` as an argument, which is like `withStream`?  If it returns the `Stream` it behaves like `useStream`?

**Comment by qualidafial** [comment]
I guess it's time for me to figure out how SQL object works.

I'll close this PR and submit a new one with the new methods as discussed.

**Comment by qualidafial** [comment]
Posted #275

**Pull request closed without merging**
