### PR TITLE
Introduce java21 artifact with initial test showing Virtual Threads at least basically work

### PR DESCRIPTION
**Pull request by stevenschlansker**

### CODE REVIEW

**Comment by stevenschlansker** [comment]
Ok, I wrote a test that doesn't work to debug deadlocks further.

**Comment by stevenschlansker** [comment]
Hi @mhib , I merged your commit into this branch and tried to test again, but unfortunately tests still seem to fail :(
Java 23 is supposed to improve the situation here a lot, so maybe once that is released we try again. Or it could be a bug in the test...

**Comment by mhib** [comment]
@stevenschlansker I think the version here https://github.com/jdbi/jdbi/pull/2597/files#diff-1f18cd26f02a0543d14b3bb7e8dd6865025ea30fc77da79dd9fbda3757f8b663R21 should be bumped to `3.45.3-SNAPSHOT` to match version from core's `pom.xml`. Without it old, `synchronized` version of `MemoizingSupplier` is being used.

**Comment by stevenschlansker** [comment]
🤦  thank you...

**Comment by stevenschlansker** [comment]
Excellent, tests pass now! Thanks!

**Comment by stevenschlansker** [comment]
requires https://github.com/jdbi/jdbi/pull/2691

**Comment by stevenschlansker** [comment]
Released hopefully for real this time as 3.45.4

**Pull request merged**
