### PR TITLE
Add support for emoji parameter in queries 😂 😎 😏 👌 🙏

### PR DESCRIPTION
**Pull request by qualidafial**

### CODE REVIEW

**Comment by qualidafial** [comment]
Note the pull request date..

**Comment by stevenschlansker** [comment]
Haha, this is pretty great.  As much as I love it though, do you think we should merge it in?

**Comment by qualidafial** [comment]
Nah, just some April Fools fun :wink:

**Comment by qualidafial** [comment]
I will add though, that it actually _works_.

**Pull request closed without merging**
