### PR TITLE
release notes

### PR DESCRIPTION
**Pull request by TheRealMarnes**
just the release notes for my merged PRs so far... Forgot some, thought others not noteworthy, figure now basically anything user-visible is worth mentioning

### CODE REVIEW

**Comment by qualidafial** [comment]
Heads up: I just pushed some release notes changes to #1152--some of which overlap with this PR

**Comment by TheRealMarnes** [comment]
I'll merge it when you've merged #1152 then

**Comment by TheRealMarnes** [comment]
@qualidafial

**Comment by qualidafial** [comment]
Thanks!

**Pull request merged**
