### PR TITLE
Handle '::' Postgres cast syntax in ColonStatementLexer

### PR DESCRIPTION
**Pull request by stevenschlansker**
heads up @orangecoding

### CODE REVIEW

**Comment by qualidafial** [comment]
Looks good. Assuming the build passes, :shipit:

**Comment by qualidafial** [comment]
Closed without merge?

**Comment by stevenschlansker** [comment]
I did it based on a rebased version, since the changes to `RELEASE_NOTES` conflicted with the other PR.

**Comment by stevenschlansker** [comment]
I also fucked up 218 vs 281 but it doesn't seem worth fixing it in the history.

**Comment by qualidafial** [comment]
¯\_(ツ)_/¯

**Pull request closed without merging**
