### PR TITLE
build with jdk16

### PR DESCRIPTION
**Pull request by stevenschlansker**
jdk 15 is dead, long live jdk 16

### CODE REVIEW

**Comment by hgschmie** [comment]
the build script still builds with 14 (and the README says so as well). If we remove 15 and replace with 16, the README also needs to be updated.

**Comment by stevenschlansker** [comment]
Blocked by https://youtrack.jetbrains.com/issue/KT-44624

**Comment by stevenschlansker** [comment]
https://github.com/spring-projects/spring-framework/issues/26770

**Comment by stevenschlansker** [comment]
Kotlin 1.5.0-RC fixes KT-44624
on to the next one...
```
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc (output-html) on project jdbi3-docs: Execution output-html of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed: (LoadError) load error: jruby/java/java_ext/java.lang -- java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @1f8d25db -> [Help 1]
```

**Comment by stevenschlansker** [comment]
Nice!  #1862 fixed that.  Now we are good to go as soon as Kotlin 1.5.0 is released :)

**Comment by stevenschlansker** [comment]
Kotlin 1.5.0 is out! :rocket:

**Pull request merged**
