### PR TITLE
Type-safe version of DBIFactoryBean

### PR DESCRIPTION
**Pull request by robfletcher**
I updated `DBIFactoryBean` to specify a generic type so it can be used to autowire by type. I had to update the Spring dependency so picked the lowest version that provided `FactoryBean<T>`. In the newer version of Spring it's also necessary to explicitly proxy the `DataSource` used by `DBIFactoryBean` for transaction-awareness.

### CODE REVIEW

**Comment by qualidafial** [comment]
@stevenschlansker You seem to be the most knowledgeable in the team on Spring. You wanna look at this?

**Comment by arteam** [comment]
If people are interested in the Spring integration for the v2 branch, I think we could try to backport this [commit](https://github.com/jdbi/jdbi/commit/e81bbe0f33c787365e602da3ebd0bf494e4b636a) from v3. My biggest concern is that it's probably not a binary-compatible change, so it may affect people who use old versions of Spring.

**Comment by qualidafial** [comment]
This is where I think it makes sense to have separate artifacts per dependency major version (or even minor, if they break compat), e.g. `jdbi3-spring3`, `jdbi3-spring4`

**Comment by stevenschlansker** [comment]
@robfletcher Thanks for the contribution -- unfortunately this is a compatibility breaking change, so at the very least I think we need to consult with other Spring users to make sure we aren't going to break too much stuff.  Another option would be to take our upcoming `jdbi3` release for a test drive, `jdbi3-spring` should be much more up to date.

**Comment by stevenschlansker** [comment]
I've reached out to the mailing list to see if anyone objects.  We'll hold this PR for a couple of days pending comment, but the code LGTM.

**Comment by robfletcher** [comment]
@stevenschlansker understood. FWIW I can imagine a `jdbi-spring` artifact, or series of artifacts, might make sense. Although I guess there's a question of how old a version of Spring do you actually want to support? Spring 3.0 is almost 7 years old now!

One other thing I'd like to do is auto-wire type things like `ResultSetMapperFactory` and `ArgumentFactory` instances into the DBI factory.

**Comment by stevenschlansker** [comment]
Right -- I'm not at all saying we should continue to support Spring 2, what I am more worried about is if someone is using Spring 4 with our `DBIFactoryBean`, upgrading JDBI to be compiled against Spring 3 may break their usage, even though they've never touched Spring 2 at all.  I'm hopeful that all our Spring users will prefer to have up to date dependencies and are OK with a minor build breakage as long as it doesn't happen often, so I would prefer to just go with this commit and avoid the complexity of managing separate artifacts, but maybe someone else will disagree...

**Comment by stevenschlansker** [comment]
We'd also totally love a PR for those features as well.  And I think they don't break compatibility so we could include them no problem.

**Comment by robfletcher** [comment]
Yeah, I think the `FactoryBean<T>` interface and anything I'd need to touch to implement auto-wiring (basically just the `@Autowired` annotation) are unlikely to result in breaking changes going forward.

**Comment by seancarroll** [comment]
I'm currently using Spring 4.3.2 with JDBI 2.73 and would be happy to help test

**Comment by stevenschlansker** [comment]
@seancarroll If you would rebuild your project with the latest `2.76-SNAPSHOT` and make sure there's no ugly surprises that'd be fantastic, thanks :)

**Comment by seancarroll** [comment]
I'm pretty sure I didn't do it in the most efficient way possible but I did rebuild with the latest and ran my unit/integration tests. I didn't encounter any issues.

**Comment by stevenschlansker** [comment]
Thanks @seancarroll I was pretty sure it'd be an easy upgrade but it's always good to check!  Thanks @robfletcher for the contribution.

**Pull request merged**
