### PR TITLE
Test oraclepki

### PR DESCRIPTION
**Pull request by stevenschlansker**

### CODE REVIEW

**Comment by qualidafial** [comment]
@stevenschlansker I've been getting build errors relating to OraclePKI--what is it?

**Comment by stevenschlansker** [comment]
I’m not entirely sure why the dependency checker sees this as needed. Does this branch improve the situation for you? I was trying to build in preparation for a release and it failed until I made these changes.

**Comment by TheRealMarnes** [comment]
> Not gonna lie.. all these shenanigans make me regret supporting Oracle DB just a teensy bit.

Oracle DB has consistently been a major regret in every project I've been on where the choice was made to use it...

**Comment by qualidafial** [comment]
I'd ask Oracle for help with this but I don't have $5000 laying around

**Comment by stevenschlansker** [comment]
Yeah, I hate Oracle.  And now I'm worried that this PR will break non-Oracle builds... I should move the dependency into a profile as well.  Will follow up.

**Comment by qualidafial** [comment]
Ok. In the meanwhile, I did confirm with a before-and-after that it fixes my build on the qualified-types branch

**Comment by qualidafial** [comment]
I _think_ you can manage a dependency outside of the profile and it's effectively a no-op if the dependency is never actually used. Worth a test if it simplifies the pom.

**Pull request merged**
