### PR TITLE
Make BeanMapper, FieldMapper honor `@ColumnName` annotations

### LINKED ISSUE #476: BeanMapper and FieldMapper should honor @ColumnName annotation

### PR DESCRIPTION
**Pull request by qualidafial**
Fixes #476.

@arteam Can you review?

### CODE REVIEW

**Comment by qualidafial** [comment]
So I'm not sure if `@BindBean` should also pay attention to `@ColumnName`. My instinct is no, because beans get bound through named parameters e.g. `:propertyName` , not as column names per se.

**Comment by arteam** [comment]
Yes, I will review shortly. Sorry for a late feedback, other things keep me
busy.
Am 12.09.2016 19:01 schrieb "Matthew Hall" <notifications@github.com>:

**Comment by stevenschlansker** [comment]
LGTM

**Comment by arteam** [comment]
LGTM as well. Looks like we start to implement more databinding features!

**Pull request merged**
