### PR TITLE
Add jdbi3-bom artifact

### PR DESCRIPTION
**Pull request by qualidafial**
Addresses #834 

@stevenschlansker Please review

### CODE REVIEW

**Comment by qualidafial** [comment]
:+1:

**Comment by stevenschlansker** [comment]
Confirmed working on one of our projects here.

```diff
--- a/spring/pom.xml
+++ b/spring/pom.xml
@@ -83,7 +83,7 @@
     <!-- library versions -->
     <dep.jackson.version>2.8.9</dep.jackson.version>
     <dep.kafka.version>0.10.2.1</dep.kafka.version>
-    <dep.jdbi3.version>3.0.0-beta1</dep.jdbi3.version>
+    <dep.jdbi3.version>3.0.0-beta2-SNAPSHOT</dep.jdbi3.version>
 
     <!-- OT module dependency versions -->
     <dep.otj-logging.version>2.2.3</dep.otj-logging.version>
@@ -1344,28 +1344,10 @@
       </dependency>
       <dependency>
         <groupId>org.jdbi</groupId>
-        <artifactId>jdbi3</artifactId>
-        <version>${dep.jdbi3.version}</version>
-      </dependency>
-      <dependency>
-        <groupId>org.jdbi</groupId>
-        <artifactId>jdbi3-guava</artifactId>
-        <version>${dep.jdbi3.version}</version>
-      </dependency>
-      <dependency>
-        <groupId>org.jdbi</groupId>
-        <artifactId>jdbi3-sqlobject</artifactId>
-        <version>${dep.jdbi3.version}</version>
-      </dependency>
-      <dependency>
-        <groupId>org.jdbi</groupId>
-        <artifactId>jdbi3-spring</artifactId>
-        <version>${dep.jdbi3.version}</version>
-      </dependency>
-      <dependency>
-        <groupId>org.jdbi</groupId>
-        <artifactId>jdbi3-postgres</artifactId>
+        <artifactId>jdbi3-bom</artifactId>
         <version>${dep.jdbi3.version}</version>
+        <type>pom</type>
+        <scope>import</scope>
       </dependency>
       <dependency>
         <groupId>org.postgresql</groupId>
```

**Comment by electrum** [comment]
I'm not sure this works correctly, since the import still picks up the `dependencyManagement` section from `jdbi3-parent`.

Simple `pom.xml` with no parent:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>bomtest</groupId>
    <artifactId>bomtest</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.jdbi</groupId>
                <artifactId>jdbi3-parent</artifactId>
                <version>3.0.0-beta2-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
    </dependencies>
</project>
```

Maven picks up the Guava version from `jdbi3-parent`:

```
$ mvn dependency:tree
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building bomtest 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ bomtest ---
[INFO] bomtest:bomtest:jar:1.0-SNAPSHOT
[INFO] \- com.google.guava:guava:jar:21.0:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.770 s
[INFO] Finished at: 2017-06-28T19:31:57-07:00
[INFO] Final Memory: 14M/309M
[INFO] ------------------------------------------------------------------------
```

**Comment by electrum** [comment]
I'm not sure how to solve this. Unfortunately, `combine.self="override"` doesn't work for `dependencyManagement`.

**Comment by qualidafial** [comment]
You're still using jdbi3-parent as the bom. Try it using jdbi3-bom.

On Jun 28, 2017 8:34 PM, "David Phillips" <notifications@github.com> wrote:

I'm not sure how to solve this. Unfortunately, combine.self="override"
doesn't work for dependencyManagement.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/jdbi/jdbi/pull/836#issuecomment-311845697>, or mute the
thread

**Comment by electrum** [comment]
Thanks, you're right! But same result when I import the correct artifact.

**Comment by stevenschlansker** [comment]
I guess we could have the `bom` artifact not inherit the parent?  That's kinda sucky though.

**Pull request merged**
