### PR TITLE
oralce12 module moved back

### LINKED ISSUE #2660: Move Oracle artifact back into main build
Originally, Oracle held their driver jars so tightly that you needed to sign a license just to download them. This led us to splitting out the Oracle build so your average developer didn't have to sign a contract with Oracle just to build jdbi.

Oracle by some turn of fate has relaxed their position, and the JARs are now generally available. And, having the build float makes maintaining release docs that refer to the oracle driver harder.

Let's move it back in.

### PR DESCRIPTION
**Pull request by stoyants**
Closes #2660

### CODE REVIEW

**Comment by stoyants** [comment]
I see there is a problem with the new module - "japicmp" plugin can't find version 3.45.1 , which is the most recent "jdbi" tag
But this is because "jdb2-oracle12" seems not to be tagged at the same time with main "jdbi" repo.
And even when I try to create the version for me locally "japicmp" complains now about version "3.45.0", because even such tag exists, maybe it was not build or pushed to maven central. The latest version there is "3.44.1"

I'm trying to sort out this for me locally.

Best regards, Stoyan

**Review by stevenschlansker — APPROVED** [review]
Well, I guess we will merge this and see what happens after we make a release.

**Comment by stevenschlansker** [comment]
Actually, I am going to try to backdate a release jar for the new artifact and see if the job will pick that up.

**Comment by stevenschlansker** [comment]
I tried to get the build working today.
I got as far as the container not becoming ready. The logs show:

```
Session altered.

   CREATE USER test IDENTIFIED BY "test" QUOTA UNLIMITED ON USERS
*
ERROR at line 1:
ORA-01109: database not open
```

I didn't figure out how to fix this. I tried updating to latest testcontainers version with no change.

**Comment by stoyants** [comment]
Hi @stevenschlansker 

I merged some commit, which came after my changes, in the "oracle12" branch and pushed to the MR. This started a new build (as my plan was).

And yes, I see the same message there: https://github.com/jdbi/jdbi/actions/runs/8990130231/job/24694783402?pr=2664

   CREATE USER test IDENTIFIED BY "test" QUOTA UNLIMITED ON USERS
*
ERROR at line 1:
ORA-01109: database not open

No idea at the moment why GitHub pipeline fails so miserably.
I know, that it sounds pathetic, but I tested on2 different computers (one native Linux and one WSL) ... all runs fine.
I will have a look again. And I don't think it is related to the Java code. I suspect it is setup / environment related.

Best Regards, Stoyan

**Comment by stoyants** [comment]
Hi @stevenschlansker,

Seems the pipeline is trying to run all 4 oracle test classes in parallel. But this creates 4 docker testcontainers at the same time. 
This is slow, in fact they interfere with each other. I extended тхе start-up timeout to 10 minutes (only to test). And ... it run out of disk space (have a look in the last build логс)

```
./23_Test Oracle versions (21-slim-faststart).txt:2024-05-08T20:28:32.0430409Z ##[warning]You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 45 MB
::::
./24_Test Oracle versions (18-slim-faststart).txt:2024-05-08T20:29:00.6337597Z ##[warning]You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 33 MB

```
I will check how to request from the pipeline to run the tests sequentially.

Best Regards,
Stoyan

**Comment by stoyants** [comment]
Hi @stevenschlansker ,
Can you please re-start the workflow? I fixed the problem with oracle12 testcontainers, but it failed again. And I see no relation between the problems and my changes.
Best regards, Stoyan.

**Comment by stevenschlansker** [comment]
Yeah, I'll take a look tonight or this weekend. Thank you for your persistence here.

**Comment by stoyants** [comment]
Hi @stevenschlansker,

Very strange, it seems pipeline is not stable. Each build fails at different step. And steps, which were fine before, are failing now. While others, which failed last build are now ok. None of them are related to my changes :)

I will give one more try.

Best Regards,
Stoyan

**Comment by stoyants** [comment]
Hi @stevenschlansker 
Finally, got a successful build. Maybe today is my lucky day.
Not much changed, only some Sonar issues.  But pipeline failed before not because of them.
I hope now it can be merged.
Best Regards, Stoyan

**Review by stevenschlansker — APPROVED** [review]
Thank you so much for your persistence here. I'll merge and we can monitor build stability after.

**Pull request merged**
