### PR TITLE
oraclejdk9 EOL -> openjdk13

### PR DESCRIPTION
**Pull request by stevenschlansker**

### CODE REVIEW

**Comment by qualidafial** [comment]
NPE inside the jdk12 compiler :facepalm:

**Comment by stevenschlansker** [comment]
Yeah, wtf??

**Comment by brianm** [comment]
I would strongly consider sticking to LTS releases (so 11, not 12)

**Comment by qualidafial** [comment]
I'd like to see us testing both, actually. That keeps us compatible with LTS releases, but also gives us notice when something breaks on a bleeding edge JDK.

Practically speaking, we're probably going to stick to JDK 8 as the baseline for several years yet, notwithstanding it being EOL'd. Adoption of JDK 9+ has been slow.

**Comment by stevenschlansker** [comment]
Yeah, note that we already test jdk11, this just replaces testing against 9 with 12.  No change to baseline requirements or source code compatibility level.

I opened this because I was having trouble with my local jdk12 and sure enough Travis has trouble too...

**Comment by stevenschlansker** [comment]
Created minimal reproducer, looks like it's the new nested Jdbi tests:

https://gist.github.com/stevenschlansker/a23cc97fb6d15fad6ae04bf54511ce62

Filed as JBS review id 9060134, will update when we have a public JBS id.

**Comment by stevenschlansker** [comment]
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8222251

**Comment by stevenschlansker** [comment]
Woohoo, finally!

**Pull request merged**
