### PR TITLE
Possible fix for https://github.com/jdbi/jdbi/issues/2078

### PR DESCRIPTION
**Pull request by doppelrittberger**
Hi, 
I created a possible fix for https://github.com/jdbi/jdbi/issues/2078 and added more test cases.
Feel free to reach out to me if there is something missing.
Best regards
Markus Ritter

### CODE REVIEW

**Comment by hgschmie** [comment]
just making sure that this is not slipping through the cracks: This is the same issue as #1968 and there are tests in #1991 for this. The problem is unfortunately not trivial to fix because JDBI allows batches to have non-uniform rows which wreaks havoc with cached argument binders. But not caching the argument binders will kill all the performance gains that the caching gives us.

This fix, while it address the "null, then non-null" use cases for some columns, is not a general fix.

**Comment by stevenschlansker** [comment]
Yes, I think this is currently the most important problem in Jdbi to fix. Unfortunately I haven't seen a solution I love yet.
I have considered whether as a stop-gap we might include a configuration option to select between "fast and strict" (no flexibility on argument type) and "slow but forgiving" (the classic behavior) so users may select the choice appropriate for their use.

Of course, finding the general solution would be much preferred. I am on vacation for two weeks though (Hello from Switzerland!) and will consider it more when I return :)

**Comment by doppelrittberger** [comment]
Hi
Thanks for your effort. At least the fix I made works for our usecases 😁 Please let me know if I can support you. 
Best regards

**Comment by hgschmie** [comment]
Closing, still tracked in #2390.

**Pull request closed without merging**
