### PR TITLE
Add a test showing that subclasses of SqlObject find statements based on the subclass name, not parent class

### PR DESCRIPTION
**Pull request by stevenschlansker**
tag @hgschmie @john9x @qualidafial

### CODE REVIEW

**Comment by stevenschlansker** [comment]
Open question: should the locator fall back to the superclass's location if the subclass doesn't have its own?

**Comment by john9x** [comment]
IMHO Do not change current behavior by default (not to fall back to the superclass) but add CSL constructor parameter to change bahavior.

**Comment by stevenschlansker** [comment]
Sounds reasonable, and either way should probably be a followup and let this PR stand alone.

**Comment by qualidafial** [comment]
> Open question: should the locator fall back to the superclass's location if the subclass doesn't have its own?

Let's hold off on this until we have evidence it's actually a problem. Seems speculative just now.

**Comment by qualidafial** [comment]
:shipit:

**Pull request merged**
