### PR TITLE
Qualifiers #1751: refactoring suggestion

### PR DESCRIPTION
**Pull request by leaumar**
suggestion for #1751 

IMO separating these concerns feels less tangly, easier on the mind, even if it is a bit more code. I think it's also quite well optimized for performance as originally intended.

### CODE REVIEW

**Comment by leaumar** [comment]
I don't know what the kotlin error is about...

**Comment by stevenschlansker** [comment]
Did you have a chance to compare performance before / after / vs my change?

**Comment by leaumar** [comment]
No, sorry. I can try to do that tomorrow if you don't do it. My focus was on code simplicity, I just tried to avoid doing anything that would be an obvious step backward in performance.

**Comment by leaumar** [comment]
Before refactor:
```
Benchmark                                     Mode  Cnt      Score      Error  Units
QualifiersBenchmark.getQualifiersAnnotated    avgt    5    225.286 ±   17.535  ns/op
QualifiersBenchmark.getQualifiersUnannotated  avgt    5    135.407 ±    6.985  ns/op
QualifiersBenchmark.mapQualifiedBean          avgt    5  32375.018 ± 1512.807  ns/op
QualifiersBenchmark.mapUnqualifiedBean        avgt    5  34898.519 ± 7136.024  ns/op
```

After refactor:
```
Benchmark                                     Mode  Cnt      Score      Error  Units
QualifiersBenchmark.getQualifiersAnnotated    avgt    5    222.257 ±   10.369  ns/op
QualifiersBenchmark.getQualifiersUnannotated  avgt    5    140.961 ±   10.855  ns/op
QualifiersBenchmark.mapQualifiedBean          avgt    5  32894.482 ± 2735.528  ns/op
QualifiersBenchmark.mapUnqualifiedBean        avgt    5  32898.203 ± 2078.309  ns/op
```

Seems to me the difference is within the margin of error, so no loss of performance?

**Comment by stevenschlansker** [comment]
Unfortunately I don't think the QualifiersBenchmark actually covers this refactoring - you'll notice it changes argument factory code, while the qualifier benchmark only tests the Qualifiers code itself.

**Comment by leaumar** [comment]
The only way it touches argument factory code is renaming the method you added in your original PR (which was one of my other review remarks), so I don't think it matters for the concern of refactoring just a part of your original PR?

**Comment by stevenschlansker** [comment]
I tried to make some comparisons but even running for 2h the results were inconclusive.
I guess I'll save this for last, get the rest merged in, then re-test and re-profile.

**Comment by stevenschlansker** [comment]
replaced by #1766

**Pull request closed without merging**
