### PR TITLE
New @DefineIn annotation for dynamic column list definition

### PR DESCRIPTION
**Pull request by mdhausman**
Added DefineIn annotation to the jdbi repository, created TestDefineInParameter.java for unit testing it.

This is for issue #512. Continued from #528.

### CODE REVIEW

**Comment by mdhausman** [comment]
With apologies to @qualidafial

**Comment by mdhausman** [comment]
Hmm, looks like it's not liking the javadoc I did. I can give it a quick touch-up if y'all want. I think just replacing the extended 
```
{@code
...
}
```
with 
```
<blockquote>
<pre>
<code>
...
</code>
</pre>
</blockquote>
```
would do the trick. Maybe replacing the `@`s with `{@literal @}`.

**Comment by mdhausman** [comment]
:tada:

**Comment by qualidafial** [comment]
Thanks Maura!

**Pull request merged**
