### PR TITLE
DBI -> Jdbi

### PR DESCRIPTION
**Pull request by stevenschlansker**
part of #353

### CODE REVIEW

**Comment by qualidafial** [comment]
👍  to this rename.

This is a good time to reconsider the naming idioms in our code. If we're renaming `DBI` to `Jdbi`, should variables be renamed too? `jdbi` is an option but I was thinking just `db` would be nice.

**Comment by stevenschlansker** [comment]
Let's do that as a followup?  I'm trying to burn down the backlog to get to `alpha0` and fixing the API is more important than the internal names :)

**Comment by stevenschlansker** [comment]
followup is #370

**Pull request merged**
