### PR TITLE
Fix typo in ColumnMapper section

### PR DESCRIPTION
**Pull request by juggernaut**
Missed replacing type variable `T` with actual type `Money`

### CODE REVIEW

**Comment by stevenschlansker** [comment]
Thanks!

**Comment by TheRealMarnes** [comment]
@stevenschlansker does modifying the doc files have any kind of impact, are there any considerations to when or how the merge happens?

**Comment by qualidafial** [comment]
The doc site is updated by running the script in the docs folder.

Ideally we should do this on every release. In practice, sometimes we forget.

**Comment by qualidafial** [comment]
Correct.

**Pull request merged**
