### PR TITLE
Generate API javadocs as part of build

### PR DESCRIPTION
**Pull request by qualidafial**
To Do

* [x] Fix core javadoc
* [x] Fix guava javadoc
* [x] Fix jodatime javadoc
* [x] Fix JPA javadoc
* [x] Fix spring javadoc
* [x] Fix sqlobject javadoc
* [x] Include and link to javadoc in doc site build

### CODE REVIEW

**Comment by qualidafial** [comment]
This is ready for review.

The main point is to generate javadoc and publish it with the site docs. There is a link on the main page to the javadoc directory.

Most of the line changes though are bringing the javadoc to the point where Maven won't bark at us. Mainly adding `@param` and `@return` javadoc tags where missing.

**Comment by qualidafial** [comment]
I published to `jdbi.github.io` so you can review the javadoc there if you like.

**Comment by qualidafial** [comment]
Let's just merge and get this moving forward

**Comment by stevenschlansker** [comment]
Awesome

**Pull request merged**
