### PR TITLE
Use Lock instead of synchronized block in MemoizingSupplier to prevent pinning

### PR DESCRIPTION
**Pull request by mhib**
The issue was caused by virtual threads waiting for the connection, as JVM was unable to unpin them while in `synchronized` block.

I've read this discussion: https://github.com/jdbi/jdbi/issues/2518#issuecomment-1875999057

But I believe `MemoizingSupplier` qualifies as a hotspot.

### CODE REVIEW

**Comment by stevenschlansker** [comment]
Hi @mhib , thanks for proposing this change.
The latest Loom EA builds promise:

> This build improves the implementation of Java monitors (synchronized methods) to work better with virtual threads.

which I hope would remove the need to change `synchronized` blocks out for locks.

Is this potential pin causing a specific problem for you that is solved with this change? I would expect the pin to be of a very short duration that would be unlikely to harm throughput, since it is only a field read, except for the first initialization.

Otherwise, we're hoping that Loom will advance to the point where we do not have to change our code to consider its implementation limitations.

**Comment by mhib** [comment]
@stevenschlansker It fixes the deadlock from https://github.com/jdbi/jdbi/pull/2597. I use jdbi with virtual threads quite a lot, but without using Jdbi plugins, so I've never encountered this scenario.

**Comment by stevenschlansker** [comment]
OK, good enough. Let's give it a spin. Thanks for looking into this.

**Review by stevenschlansker — APPROVED** [review]

**Comment by mhib** [comment]
@stevenschlansker Note that the taget branch of this pull request was set to the branch from this: https://github.com/jdbi/jdbi/pull/2597, not the `master` branch. I'm sorry If I should have underlined it more.

**Comment by stevenschlansker** [comment]
Oops, sorry I totally missed that. Will look again this week.

**Pull request merged**
