### PR TITLE
Re-enable parallel testing for jdbi3.

### PR DESCRIPTION
**Pull request by stevenschlansker**
undoes #332

### CODE REVIEW

**Comment by qualidafial** [comment]
:shipit:

**Comment by stevenschlansker** [comment]
rebased / merged

**Comment by qualidafial** [comment]
This is making my builds hang again..

**Comment by qualidafial** [comment]
Can we revert this?

**Comment by stevenschlansker** [comment]
Yes, if it's not fixed on the main branch by now (with the parent POM update) go ahead and revert.

**Pull request closed without merging**
